### ISSUE TITLE
Reactants from reagent list do not appear above reaction arrow

### ISSUE THREAD

**Issue by MiroHalacz** [ComPlat/chemotion_ELN#1267]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

Reactants should appear above the reaction arrow

# Current Behavior

Reactants do not appear above reaction arrow, if two reactans are added, a plus-symbol appears, but no reactants.
Only for reactants  from reagents list, per drag and drop it works,
# Failure Information 
Just upgraded last week to 1.5.1, before i did not observe this problem.

## Steps to Reproduce

1. create new reaction or modify existing old reaction
2. add reactant  from reagents list
3. -> no reactant above arrow
4. add reactant from own collection -> works fine
5. Example in Screenshot: Phthalimide from own collection and 3 reactants from reagent-dropdown list

## Context
 - OS: Windows 10 Pro
 - Chrome Browser 
 - ELN version 1.5.1

## Failure Logs / Screenshots

Include any relevant log snippets or files here.
![Screenshot (15)](https://user-images.githubusercontent.com/113168734/231092516-f1041796-620b-40c2-b163-5a781aca2ce7.png)

**Comment by endevor-music** [comment]
Please see the following video for a workaround whilst the issue is being investigated. 

Workaround:

- save reaction (to allow links to reagent samples to be generated)
- click reagent to open details window
- click on reagent image to open molecule editor modal
- save molecule editor and save and close reagent details window
- reagent should now be visible in reaction image

https://user-images.githubusercontent.com/67055123/234805592-77093f46-f248-4913-a778-94b51ef462b5.mp4

**Comment by endevor-music** [comment]
> Please see the following video for a workaround whilst the issue is being investigated.
> 
> Workaround:
> 
> * save reaction (to allow links to reagent samples to be generated)
> * click reagent to open details window
> * click on reagent image to open molecule editor modal
> * save molecule editor and save and close reagent details window
> * reagent should now be visible in reaction image
> 
>  Chemotion.dev.-.Google.Chrome.2023-04-27.09-57-35_Trim.mp4

An easier alternative is toggling the L/S button to show the label instead of the image
