### ISSUE TITLE
Add (fluorescence) emission layout for chemspectra

### ISSUE THREAD

**Issue by baolanlequang** [ComPlat/chemotion_ELN#1372]
- I am a developer

# Description
New layout for fluorescence emission data.
X axis = wavelength (nm)
Y axis = Intensity
Features: peak picking and reports peaks as a list of XY values.

**Comment by schatzsc** [comment]
Please keep in mind that in luminescence spectroscopy, there are two different modes of measurement that both give rise to a intensity vs. wavelength output:

a) the **emission spectra** in a strict sense, in which a fixed excitation wavelength is focused on the sample and the (lower energy = red-shifted) emission recorded and

b) the so-called **excitation spectrum** in which the "output wavelength" is kept fixed and the (higher-energy = blue-shifted) excitation wavelength is scanned in order to find the excitation wavelength that gives the strongest emission.

For both measurement modes, it is also strictly required to record - in addition to the x/y data, the mode (excitation or emission) and the fixed wavelength (either excitation or emission) as this otherwise cannot be deduced from the measurement itself.

Finally, if you are thinking about luminescence spectroscopy in more general terms, there is often also a third type of measurement, which records emission intensity at a fixed wavelength over time.

And usually, the lifetimes and quantum yields are also recorded in a tabular format.

**Comment by f-idiris** [comment]
Thanks a lot for your input. This layout is strictly for plotting and reporting Emission spectra and in the future we will have another layout specifically for Excitation spectra. 

Both layouts will report the fixed (excitation or emission) wavelength and for this functionality we will create a separate issue.
