### ISSUE TITLE
DOI not accepted

### ISSUE THREAD

**Issue by Alexwelle1** [ComPlat/chemotion_ELN#1417]
- I am an ELNer: YES
- I am a developer
- I am a system/ELN admin

# Expected Behavior

Not sure, but I think based on a provided DOI, the system will add meta data

# Current Behavior

Tried this DOI: 10.1002/1097-4636(20011205)57:3<432::AID-JBM1186>3.0.CO;2-G 
Made sure on https://dx.doi.org/ that it usually works.

# Failure Information 
Eoor message: Unable to fetch meta data ...

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Open new research plan
Add the DOI above

## Context

 - Chrome Browser 
 - Firefox Browser
 - ELN version: KNMFi installation at KIT

**Comment by FabianMauz** [comment]
The problem is that the entered DOI is a SICI 
https://en.wikipedia.org/wiki/Serial_Item_and_Contribution_Identifier

The current library does not support that type of identifier. There is an open issue in the library project: 

https://github.com/citation-js/citation-js/issues/182

and one of the authors said SICI will not be included.
