### ISSUE TITLE
Add units for system-defined inputs

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#1453]
- I am an ELNer
   - I am a system/ELN admin

I suggest to add the following system-defined inputs' units:

    [eV] and  [keV] for Energy
    [µm] for Length

**Comment by cllde8** [comment]
Dear @martin-held-hereon, 

After review, these units have been available since ELN 1.8.x.

You can find the full list at [this link](https://github.com/LabIMotion/labimotion/wiki/Supported-Units-of-System-Defined-Field).

If you have any further questions or suggestions, please don't hesitate to create an issue or discussion on our GitHub repository: https://github.com/LabIMotion/labimotion.

Thank you.

Best regards,
Claire

**Comment by martin-held-hereon** [comment]
[µm] for Length ... is not available according to the list!
