### ISSUE TITLE
Drag sample in generic segment

### ISSUE THREAD

**Issue by martin-held-hereon** [ComPlat/chemotion_ELN#1457]
- I am an ELNer 
- I am a system/ELN admin

# Description
I would like to revive issue #401 and ask for the "drag sample" option in generic segments! At the moment, this is only available in the properties segment of a generic element.

**Comment by cllde8** [comment]
Dear @martin-held-hereon, 

After review, the "drag sample to generic segment" feature has been available since LabIMotion 1.1.0, which was included in ELN 1.8.1.

If you have any further questions or suggestions, please feel free to create an issue or discussion at https://github.com/LabIMotion/labimotion.

Thank you.

Best regards,
Claire

**Comment by martin-held-hereon** [comment]
I tested this successfully! thanks!
