### ISSUE TITLE
"+ add analysis" button

### ISSUE THREAD

**Issue by SimoneGraessle** [ComPlat/chemotion_ELN#1459]
I have a question:
Why did you delete the green "+ add analysis" button below the analyses?
This button is only above the analyses. In the last version, however, this button was also below the analyses. 

It would be very good if you could add this button back below the analyses as well. 
If you have already added many analyses, you always have to scroll up to add a new analysis and scroll down again to fill it. 

Thanks and best wishes, 
Simone

**Comment by endevor-music** [comment]
Hi @SimoneGraessle,

It seems the analyses tab has had a new enhancement - switching between "Edit mode" and "Order Mode".

In Order mode, the button is still present, but this is not the case in the Edit mode.

Edit Mode:
![Screenshot 2023-08-07 084234](https://github.com/ComPlat/chemotion_ELN/assets/67055123/a9c3f1ca-9a2e-4e21-aa77-ea252ca1e6d1)

Order Mode
![Screenshot 2023-08-07 084258](https://github.com/ComPlat/chemotion_ELN/assets/67055123/7f915046-d525-4e5d-8bf3-e1a94609f16f)

Despite this, I do agree that in the case of having multiple analyses, it is inconvenient to have to scroll up and down to add new analyses. I shall discuss with the team today.

Thanks,
Dev

**Comment by mekkyz** [comment]
Hi @SimoneGraessle,

The idea was to make it so that we don't have two buttons on same page for one action.

For the case of many analyses, I have fixed the buttons row position to be always visible.

See the video below: 

[Screencast from 09.08.2023 11:05:42.webm](https://github.com/ComPlat/chemotion_ELN/assets/59936007/8ff51eb6-c729-4347-9f7f-f062bdb874e7)

**Comment by SimoneGraessle** [comment]
Pefect, that is a good solution. 

Thank you very much :)
