### ISSUE TITLE
Data upload for Meta data extraction only

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1701]
- I am an ELN admin

# Description
At our University the storage capacity for an ELN Server is limited to a degree that prohibits the storage of datasets in Chemotion. Instead we use file links in the Hyperlink field (the respective file system is Insolated from the Chemotion server by firewall). 
It  would be very helpful if it was possible to automatically add meta data to an analysis dataset as follows:

1. upload the data set of an analysis to the server
2. Chemotion extracts the meta data from the data set to fill the generic dataset of LabIMotion
3. INSTEAD of storing the uploaded/converted file(s) on the Chemotion Server the files are discared
4. the analysis data set holds ONLY the auto filled LabIMotion generic meta data
5. the user enters a file link into the Hyperlink field of the data set

**Comment by phuang26** [comment]
@MichaelOCI I believe it would be more beneficial to retain the data rather than discarding it. If the issue is related to server storage capacity, linking to an external storage solution could be a viable option. For instance, external file storage or AWS S3 could be considered. 

However, if discarding files after processing is desired, configuring the storage as memory storage could be a solution.
