### ISSUE TITLE
Improve Docker setup

### ISSUE THREAD

**Issue by flange-science** [ComPlat/chemotion_ELN#347]
I've spend the whole day getting Chemotion to run with Docker according to INSTALL.md - including high levels of frustration. These are my impressions:
- `docker-compose build` runs through smoothly.
- Don't execute `docker-compose` more than once as this creates new containers over and over again. For step 2 I used the interactive shell after running `docker-compose up` (ONCE!).
- 'bundle exec rake db:migrate' fails, because it is unable to to find storage.yml and database.yml. I'm not sure if the `cp` command for them is done in the right directory in Dockerfile.
- `rake ketcherails:import:common_templates` fails:
unknown file type: /usr/local/rvm/gems/ruby-2.3.3/bundler/gems/ketcher-rails-bbc54084cd63/public/images/ketcherails/seeds/icons/icon/AA3.png
/usr/local/rvm/gems/ruby-2.3.3/bundler/gems/ketcher-rails-bbc54084cd63/lib/tasks/ketcherails.rake:17:in `block in copy_icons_files' ...
- Exposing port 80 instead of 3000 would be more intuitive.

**Comment by CamAnNguyen** [comment]
Hello @flange-ipb , thank you for your interesting and feedback about our project. We will update the instructions `INSTALL.md` to be more understandable in the next release of the ELN. 

- `docker-compose`: Your way would be better. More clean, no unnecessary container. However, I think it would be easier and simpler for chemist/scientist rather than connect to the container itself and make the changes. Moreover, some addition container does not consume much disk space.

- `bundle exec rake db:migrate`: It seems that we did not instruct clear enough in the `INSTALL.md`. But please check the `BASIC SETUP` part, it contains the `config/database.yml` and `config/storage.yml` files setup.

- `rake ketcherails:import:common_templates`: I am sorry about this issue, this step is optional for the pre-defined template which will be used inside the Ketcher Editor. You can skip it without any further problem with the project. If you still want to run this, please update the `ketcherails` line in the `Gemfile`: from `ref: 'bbc54084cd6365bcc9229dfe43f8e7dc8c16a845'` to `ref: '19b5bd5344462295a2633ccfefed8a5bb4f85f28'`

- You can totally change this with `docker-compose.yml` file.
