### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by curtisd0886** [ComPlat/chemotion_ELN#362]
Hello, I am attempting to install Chemotion on a Ubuntu server and when I run the install script I get the following error "E: The repository 'http://cran.rstudio.com/bin/linux/ubuntu bionic/ Release' does not have a Release file.". Do you know what may be causing this issue?

**Comment by CamAnNguyen** [comment]
Hi @curtisd0886 , this error is due to your repository server of the `cran` package. This source is not configured properly so that it cause the `apt-get update` command to have this error. 
To resolve this, you can follow these steps:
- Edit `/etc/apt/sources.list` file with `su` permission and remove cran-related line. 
- Add your `cran` package again: `deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/`
- `sudo apt-get update`

After that, you should be able to run the install script again
