### ISSUE TITLE
Shibboleth Identity Provider needed

### ISSUE THREAD

**Issue by boontifex** [ComPlat/chemotion_ELN#535]
For production use we need further authentication methods, in our case SAML (f.e. with shibboleth).

**Comment by paulstueve** [comment]
I would like to support and expand this issue: in order to be able to offer Chemotion as a service, we depend on the possibility to integrate LDAP and Shibboleth for authentication, and to disable self-registration.

**Comment by schatzsc** [comment]
I would like to strongly support this issue.

We plan to roll out Chemotion on a Faculty scale to about 30-40 research groups with a total of several hundred users at the maximum stage from Postdoc and permanent staff to short-term Bachelor projects via the computer center of our university and need more structured control of access rights and user management.

Currently, with only two levels ("normal user" and "administrator"), the structure is too "flat" and results in a situation where either 1) a very small number of admin users will have to do too much work beyond the maintenance of the installation itself or 2) too many users will have very high full admin right.s

**Comment by GU-uzun** [comment]
I would like to push this issue too. It's an important feature for me too.

**Comment by HenningTimm** [comment]
Is there any news if this feature is still in development? It has been "urgent" for well over a year now and I cannot find any mentions in the code, but that could just be me searching wrong ;)

Currently the lack of support for authentication via SAML or LDAP is preventing us from operating Chemotion as a service at our institution since we face the same scaling problem as described by @schatzsc. Having a rough estimate if and when this feature could be available would be very helpful for our planning.

**Comment by schatzsc** [comment]
It was mentioned in the last NFDI4Chem TA2 meeting that Shibboleth support will be included in the upcoming v1.5.1 version, which is expected to be released within the next 2-4 weeks.

Just a little bit more patience, please. We are also urgently waiting for this feature ...

**Comment by schatzsc** [comment]
I'm still a bit confused - is this functionality now in v1.5.1 or not, because the changelog at

https://github.com/ComPlat/chemotion_ELN/releases/tag/v1.5.1

does not mention it specifically?!? The highest pull request mentioned there is #1236 but #1239 is higher.

If not included, when to you expect Shibboleth to be incorporated? We are super-urgently waiting for it and cannot proceed with the faculty-wide installation of Chemotion without it ...

**Comment by PiTrem** [comment]
@schatzsc 

Shibboleth is now available with [v1.6.0-rc0](https://github.com/ComPlat/chemotion_ELN/blob/main/CHANGELOG.md#pre-v160)  (which is just  v1.5.1 + shibb authentication).
The docker images will be available shortly.

**Comment by phuang26** [comment]
Hi @crsoph, while the documentation for Shibboleth is still in progress, I would be happy to assist you with the installation and configuration of Shibboleth through a meeting, please send me an email if it works for you. My email is: [pei-chi.huang@kit.edu](mailto:pei-chi.huang@kit.edu)

**Comment by sasscz** [comment]
Hello all,
Is there already an update on the documentation for Shibboleth? On the documentation website, for example, there are still no sample parameters listed. For us, a connection to Shibboleth is necessary to be able to offer the software.
Is there an example configuration or similar?
Kind regards
Sascha

**Comment by PiTrem** [comment]
for the record: 
https://chemotion.net/docs/eln/install_configure/authentication
